version: 2

# inspired by https://github.com/ergebnis/phpstan-rules/blob/main/.github/dependabot.yaml

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    open-pull-requests-limit: 15
    commit-message:
      include: "scope"
      prefix: "github-actions"
